package client.gui;

import javax.swing.JScrollPane;

import client.gui.synchronization.BatchState;

public class FormEntryPanel extends JScrollPane {
	
	BatchState bchS;

	/**
	 * Auto Generated by Eclipse
	 */
	private static final long serialVersionUID = 1L;
	
	public FormEntryPanel(BatchState bchS){
		this.bchS = bchS;
		this.createComponents();
	}
	
	private void createComponents(){
		
	}
	

}
