package client.gui;

import javax.swing.JFrame;

public class MainFrame extends JFrame {

	/**
	 * Default generated serial version UID--generated by Eclipse
	 */
	private static final long serialVersionUID = 1L;
	
	/**
	 * Main method
	 * @param args
	 */
	public static void main(String[] args){
		LoginFrame login = new LoginFrame("localhost", 8080);
		login.pack();
		login.setVisible(true);
	}
	
	public MainFrame() {
		
	}
	
	
	

}
