package client.gui;

import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

import client.gui.synchronization.WindowManager;
import client.gui.synchronization.WindowManagerListener;
import shared.model.User;

public class MainFrame extends JFrame implements WindowManagerListener {

	/**
	 * Default generated serial version UID--generated by Eclipse
	 */
	private static final long serialVersionUID = 1L;
	
	//Non static methods and variables
	//Global Variables
	String server_host;
	int server_port;
	User user;
	JMenuBar menuBar;
	JMenu menu;
	JMenuItem downloadBatchMenuOption;
	JMenuItem logoutMenuOption;
	JMenuItem exitMenuOption;
	WindowManager wManager;
	
	
	public MainFrame(String server_host, int server_port, User user, WindowManager wManager) {
		this.user = user;
		this.server_host = server_host;
		this.server_port = server_port;
		this.wManager = wManager;
		this.wManager.addListener(this);
	}
	
	private void createComponents(){
		//Create the menubar and the menu
		menuBar = new JMenuBar();
		
		menu = new JMenu("File");
		
		downloadBatchMenuOption = new JMenuItem("Download Batch");
		logoutMenuOption = new JMenuItem("Logout");
		exitMenuOption = new JMenuItem("Exit");
		
		menu.add(downloadBatchMenuOption);
		menu.add(logoutMenuOption);
		menu.add(exitMenuOption);
		menuBar.add(menu);
		
		this.add(menuBar);

		
	}

	@Override
	public void visibilityToggled(boolean loginWindowVisible,
			boolean mainWindowVisible, User currUser) {
		if(!mainWindowVisible){
			this.setVisible(false);
		}
		else{
			this.user = currUser;
			createComponents();
			this.setVisible(true);
		}
		
	}
	
	
	

}
